name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@fa23c36f1c387d44be9f1bc52144744224683908#egg=discrete-optimization
      - nbgitpuller
