name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@955bce1905f7f35847b06b6d0c263b8ead45ad86#egg=discrete-optimization
      - nbgitpuller
