name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@dbad4dab69ccc635ebb5ff7e9a8e685b8e7b92a7#egg=discrete-optimization
      - nbgitpuller
