name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@668dcb76e57b3c128bcf3458c25bd5894a88e330#egg=discrete-optimization
      - nbgitpuller
