name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@801948037e828498ec2d770149d7332999b00e9f#egg=discrete-optimization
      - nbgitpuller
