name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@6c31066b11d5b945e0f18d88c65accfdf462eb15#egg=discrete-optimization
      - nbgitpuller
