name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@e3ce6d213788d15ee585417a2a835dc70e867b2a#egg=discrete-optimization
      - nbgitpuller
