name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@71f01c1723897a161de32750a8de854e175ad2ae#egg=discrete-optimization
      - nbgitpuller
