name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@efeddce804f8ab838731b29e42164f2261e7ffa2#egg=discrete-optimization
      - nbgitpuller
