name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@677615eaf8eaa7c26734e7cdeace3bb0938ebe83#egg=discrete-optimization
      - nbgitpuller
