name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@e9224e08f3f631a2d1339ae77a1e213b58914ebb#egg=discrete-optimization
      - nbgitpuller
