name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@f45ca2e90845eeb60608e0b7fbdc0b9aa1221bde#egg=discrete-optimization
      - nbgitpuller
