name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@3c905f609cc942e526c81c4834412580375bb6d0#egg=discrete-optimization
      - nbgitpuller
