name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@c5597cbfb29677689cd75afa0ee78679a6249399#egg=discrete-optimization
      - nbgitpuller
